### ISSUE TITLE
Multi-node training fails due to NCCL error

### ISSUE THREAD

**Issue by domenVres** [NVIDIA/NeMo#13996]
**Describe the bug**

In the newest versions of NeMo prebuilt container (25.04 and later) multi-node training fails due to the following NCCL error:
`graph/topo.h:230 NCCL WARN Could not find NET with id 0`

The error occurred during the supervised fine-tuning of the Gemma 2 model, but I suspect the issue should appear in other training scenarios with other models as well, as it happens immediately after all processes are registered:
```
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 32 processes
----------------------------------------------------------------------------------------------------
```

The error happens only in a multi-node scenario (I tested training in a single-node scenario as well, and it was fine). It happened on 2 Euro HPC clusters (LEONARDO and Vega) that use IB communication between nodes.

I tested the upgrading of NCCL to the newest version, and **it solved the problem.** Specifically, I upgraded the container to NCCL 2.27.3 for CUDA 12.9 from https://developer.nvidia.com/nccl/nccl-download. **Hence, I ask you to update the NCCL version in the following container releases.**

I am also including the Python traceback of the error:

```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/script/gemma_sft.py", line 144, in <module>
[rank4]:     pretrain_fn()
[rank4]:   File "/opt/NeMo/nemo/collections/llm/api.py", line 222, in finetune
[rank4]:     return train(
[rank4]:            ^^^^^^
[rank4]:   File "/opt/NeMo/nemo/collections/llm/api.py", line 127, in train
[rank4]:     trainer.fit(model, data)
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
[rank4]:     call._call_and_handle_interrupt(
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank4]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
[rank4]:     return function(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
[rank4]:     self._run(model, ckpt_path=ckpt_path)
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/trainer.py", line 943, in _run
[rank4]:     call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
[rank4]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/trainer/call.py", line 99, in _call_setup_hook
[rank4]:     trainer.strategy.barrier("pre_setup")
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/lightning/pytorch/strategies/ddp.py", line 297, in barrier
[rank4]:     torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank4]:     return func(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/distributed_c10d.py", line 4553, in barrier
[rank4]:     work = group.barrier(opts=opts)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]: torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:3376, internal error - please report this issue to the NCCL developers, NCCL version 2.25.1
[rank4]: ncclInternalError: Internal check failed.
[rank4]: Last error:
[rank4]: Could not find NET with id 0
```

**Steps/Code to reproduce bug**

Run the SFT of the Gemma 2 model in a multi-node scenario on an EuroHPC cluster.

**Expected behavior**

Updated NCCL library inside the official NeMo container so the multi-node training is working.

**Environment overview (please complete the following information)**

 - Environment location: 2 EuroHPC clusters using A100 GPUs, SLURM and IB communication between nodes. Clusters:
     - LEONARDO (Booster partition): https://www.hpc.cineca.it/systems/hardware/leonardo/
     - Vega: https://doc.vega.izum.si/architecture/
 - Method of NeMo install: official NeMo container (25.04, 25.04.01)

**Comment by pramodk** [comment]
Just cross-referencing  #13854 here.

**Comment by pramodk** [comment]
> It happened on 2 Euro HPC clusters (LEONARDO and Vega) that use IB communication between nodes.
> Specifically, I upgraded the container to NCCL 2.27.3 for CUDA 12.9 from https://developer.nvidia.com/nccl/nccl-download. 

@domenVres: thanks for providing this info! As per the the NCCL [release notes](https://docs.nvidia.com/deeplearning/nccl/pdf/NCCL-Release-Notes.pdf), we see support for CUDA 12.9 with NCCL release >=2.26.5. (The NeMo 25.04 container comes with CUDA 12.8 and NCCL 2.25.1).

Out of curiosity, what CUDA and CUDA driver versions are installed on these two systems?


> Hence, I ask you to update the NCCL version in the following container releases.

As far as I see, next release of NGC container would be based on [PyTorch 25.05](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-25-04.html#rel-25-04) container and will come up with CUDA 12.9 and NCCL 2.27.3. So this will be resolved soon.

**Comment by domenVres** [comment]
> [@domenVres](https://github.com/domenVres): thanks for providing this info! As per the the NCCL [release notes](https://docs.nvidia.com/deeplearning/nccl/pdf/NCCL-Release-Notes.pdf), we see support for CUDA 12.9 with NCCL release >=2.26.5. (The NeMo 25.04 container comes with CUDA 12.8 and NCCL 2.25.1).
> 
> Out of curiosity, what CUDA and CUDA driver versions are installed on these two systems?

Thank you for the information (I also noticed that NCCL is meant for CUDA 12.9; however, I risked installing it into the NeMo container with 12.8, and somehow it worked). Regarding the Driver and CUDA versions on the cluster, they are a bit older (especially LEONARDO), however, as mentioned before, I am using the NeMo container and hence the versions that are in there. Cluster versions are following:

- LEONARDO: CUDA Version: 12.1, Driver Version: 530.30.02
- Vega: CUDA Version 12.7, Driver Version: 565.57.01

**Comment by pramodk** [comment]
@domenVres : I am curious if the behavior is changed with the recently released 25.07 container. Could you please give a try and let us know the outcome? That would be very helpful.

**Comment by janEbert** [comment]
~~Hey, I'm not OP but can confirm resolution with PyTorch NGC 25.06, probably already fixed with 25.05. :)~~
Sorry, misread what you were asking for.

**Comment by domenVres** [comment]
> [@domenVres](https://github.com/domenVres) : I am curious if the behavior is changed with the recently released 25.07 container. Could you please give a try and let us know the outcome? That would be very helpful.

Apologies for late reply, I was busy with other work. I tested the new container (25.07) on Leonardo and can confirm that the issue is resolved.

**Comment by pramodk** [comment]
Thanks for confirming @domenVres!
