### ISSUE TITLE
transcribe failed

### ISSUE THREAD

**Issue by wen1q84** [NVIDIA/NeMo#14107]
**Describe the bug**
When I  the nvidia/stt_en_fastconformer_transducer_large model from huggingface to do a simple speech recognition, I encountered the following error
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 772, in _full_graph_compile
    outer_loop_kernel = self._create_outer_while_loop_kernel()
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 615, in _create_outer_while_loop_kernel
    return run_nvrtc(kernel_string, b"outer_loop_labels_conditional", cls.CUDA_PROGRAM_NAME)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/core/utils/cuda_python_utils.py", line 222, in run_nvrtc
    assert_drv(err)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/core/utils/cuda_python_utils.py", line 79, in assert_drv
    raise RuntimeError("Cuda Error: {}".format(err))
RuntimeError: Cuda Error: 222

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/models/rnnt_models.py", line 307, in transcribe
    return super().transcribe(
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/mixins/transcription.py", line 269, in transcribe
    for processed_outputs in generator:
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/mixins/transcription.py", line 380, in transcribe_generator
    processed_outputs = self._transcribe_output_processing(model_outputs, transcribe_cfg)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/models/rnnt_models.py", line 945, in _transcribe_output_processing
    hyp = self.decoding.rnnt_decoder_predictions_tensor(
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_decoding.py", line 522, in rnnt_decoder_predictions_tensor
    hypotheses_list = self.decoding(
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_greedy_decoding.py", line 198, in __call__
    return self.forward(*args, **kwargs)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/core/classes/common.py", line 1081, in wrapped_call
    outputs = wrapped(*args, **kwargs)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_greedy_decoding.py", line 745, in forward
    hypotheses = self._greedy_decode(
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_greedy_decoding.py", line 773, in _greedy_decode_blank_as_pad_loop_labels
    batched_hyps, alignments, last_decoder_state = self._decoding_computer(x=x, out_len=out_len)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 1032, in __call__
    return self.loop_labels_cuda_graphs(encoder_output=x, encoder_output_length=out_len)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 563, in loop_labels_cuda_graphs
    self._graph_reinitialize(encoder_output, encoder_output_length)
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 680, in _graph_reinitialize
    self._full_graph_compile()
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/rnnt_loop_labels_computer.py", line 758, in _full_graph_compile
    with (
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/root/miniconda3/envs/nemo/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: invalid argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Steps/Code to reproduce bug**

```
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained(model_name="nvidia/stt_en_fastconformer_transducer_large")
asr_model.transcribe(["xxx.wav"])
```

**Expected behavior**

transcribe success

**Environment overview (please complete the following information)**

 - Environment location: local
 - Method of NeMo install: pip install "nemo_toolkit[all]"

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 22.04.1 LTS
- PyTorch version:2.7.1
- Python version:3.10.18

**Additional context**

Example: RTX3080

**Comment by nithinraok** [comment]
Looks like a CUDA env issue while performing inference with CUDA graphs enabled. Try re-installation CUDA version and retry. or temporary workaround:
```python
asr_model.decoding.decoding_strategy = "greedy"  # If not already
asr_model.decoding.greedy.use_cuda_graph_decoder=false
```

**Comment by alvarobartt** [comment]
Hey @nithinraok I can confirm that on a fresh CUDA environment the following also fails with the same error i.e., `RuntimeError: Cuda Error: 222`:

```python
import nemo.collections.asr as nemo_asr

asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name="nvidia/parakeet-tdt-0.6b-v2")
# wget https://dldata-public.s3.us-east-2.amazonaws.com/2086-149220-0033.wav
output = asr_model.transcribe(['2086-149220-0033.wav'])
print(output[0].text)
```

Which is the example in https://huggingface.co/nvidia/parakeet-tdt-0.6b-v2#how-to-use-this-model, could you try to reproduce and if it works on your end, share the output of `pip freeze` or similar? As it might be related to PyTorch versioning issues, `cuda-python`, etc.

Thanks in advance @nithinraok 🤗 

**Update**: I tried with PyTorch 2.5.1 and 2.6.0 (on CUDA 12.4) and it seems to be working just fine, whereas on latest PyTorch i.e., 2.7.1 it won't due to the CUDA Graphs issue aforementioned (for context `cuda-python` version is 12.9.0), cc @wen1q84 as it might solve your issue too!

**Comment by wen1q84** [comment]
I solved this problem in another way: changing machine.
I move to a 4080 machine and install nemo by `pip install "nemo_toolkit[all]"` with pytorch version 2.7.1, everything is ok.
And when I go back to previous machine(3080), try this method:
```
asr_model.decoding.decoding_strategy = "greedy"  # If not already
asr_model.decoding.greedy.use_cuda_graph_decoder=false
```
Unfortunately, it doesn't work.
Then I tried downgrading pytorch to 2.6.0, it works.
thanks @nithinraok @alvarobartt .

**Comment by alvarobartt** [comment]
Fair @wen1q84 I tried on different instances NVIDIA L40S, NVIDIA L4, NVIDIA H100 (all on CUDA 12.4), and all those were failing for the NVIDIA Parakeet in the `transcribe` method, and then downgrading to PyTorch < 2.7.0 it was working just fine.

**Comment by nithinraok** [comment]
@artbataev FYI

**Comment by artbataev** [comment]
Several notes on CUDA graphs:
- check the driver version and upgrade to the latest available - I encountered many issues with drivers, now using `575` without any failures
- use CUDA version `>= 12.6`. According to https://pytorch.org/ there are 3 official PyTorch builds with `11.8`, `12.6` and `12.8` CUDA (11.8 will not work with CUDA graphs, 12.6 should work fine)
- use `greedy_batch` (not slow `greedy`) strategy with `use_cuda_graph_decoder=false` in case of any issues with CUDA graphs
- if there is a need to change decoding strategy, use `change_decoding_stragety` function instead of direct assigning `asr_model.decoding.greedy.use_cuda_graph_decoder=false`

E.g., 

```python
from omegaconf import open_dict
decoding_cfg = asr_model.cfg.decoding
with open_dict(decoding_cfg):
    decoding_cfg.strategy = "greedy_batch"
    decoding_cfg.use_cuda_graph_decoder = False
asr_model.change_decoding_strategy(decoding_cfg)
```

**Comment by sadi304** [comment]
Faced same issue. Used cuda v12.4.0. Driver is 535. 

When used `use_cuda_graph_decoder = False` it works. But slowed it down.

**Comment by KeremTurgutlu** [comment]
Upgrading nvidia driver to 575 fixed the issue for me
