### ISSUE TITLE
Export checkpoint to HuggingFace requires all GPUs

### ISSUE THREAD

**Issue by shaltielshmid** [NVIDIA/NeMo#14374]
**Describe the bug**

I'm training a model on an 8xH100 machine, using TransformerEngine and the FP8 plugin. 

When I try to export a checkpoint mid-train to HF, I get an error that there is not enough GPU memory available - it seems to load the whole sharded checkpoint onto the GPUs before exporting. 

When I try to copy the checkpoint to a new machine - the export fails unless I am using a machine 8 GPUs that support FP8 training. 

In addition, when I run the export - it fails unless I specify CUDA_LAUNCH_BLOCKING=1. 

**Steps/Code to reproduce bug**

Setup:
- 8xH100 on LambdaLabs
- Container: nvcr.io/nvidia/nemo:dev 

Step 1: Train a model:

```python
from nemo.collections import llm
from nemo.collections.llm.recipes.precision.mixed_precision import bf16_with_fp8_mixed
import nemo_run as run

recipe = llm.qwen2_1p5b.pretrain_recipe(name="pt", dir="./checkpoints", num_nodes=1, num_gpus_per_node=8)
recipe.trainer.plugins = bf16_with_fp8_mixed()

run.run(recipe, executor=run.LocalExecutor())
```

Step 2: After the first checkpoint is saved:

*export.py*
```python
from nemo.collections import llm
llm.export_ckpt("./checkpoints/pt/checkpoints/....-last", "hf", "./hf_export/", overwrite=True)
```

If I just run `python export.py`:

```text
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/tensor/float8_tensor.py", line 417, in quantize_
[rank0]:     self._get_quantizer().update_quantized(tensor, self, noop_flag=noop_flag)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/tensor/float8_tensor.py", line 79, in update_quantized
[rank0]:     src = [src.to](http://src.to/)(device=dst.device)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[rank0]:  when instantiating TELayerNormColumnParallelLinear when instantiating SelfAttention when instantiating TransformerLayer
```

If I run `CUDA_LAUNCH_BLOCKING=1 python export.py`:

```text
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/tensor/float8_tensor.py", line 417, in quantize_
[rank0]:     self._get_quantizer().update_quantized(tensor, self, noop_flag=noop_flag)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/tensor/float8_tensor.py", line 79, in update_quantized
[rank0]:     src = [src.to](http://src.to/)(device=dst.device)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacity of 79.19 GiB of which 239.44 MiB is free. Process 2672602 has 65.96 GiB memory in use. Including non-PyTorch memory, this process has 12.88 GiB memory in use. Of the allocated memory 11.67 GiB is allocated by PyTorch, and 553.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) when instantiating TELayerNormColumnParallelLinear when instantiating MLP when instantiating TransformerLayer
```

**Expected behavior**

I would expect/want the export to happen on CPU so that I wouldn't require pausing the train to export. Also, the nemo_load by default is supposed to load onto CPU:
https://github.com/NVIDIA/NeMo/blob/3d2d2abcc7ebb35f5f105b1e0eef88a583fdf3e5/nemo/lightning/io/connector.py#L218

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of install: `docker pull nvcr.io/nvidia/nemo:dev` & `docker run --rm --gpus all --network host --shm-size=8g -v $(pwd):/home/ubuntu -w /home/ubuntu nvcr.io/nvidia/nemo:dev`

**Comment by shaltielshmid** [comment]
Update: I believe this issue only occurs when using the TE+FP8 plugin. 

This causes another issue, and this line doesn't work:

https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/gpt/model/qwen2.py#L324-L325

To replicate, pause the training after the first checkpoint and try to export with CUDA_LAUNCH_BLOCKING=1:

```text
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py", line 3974, in save_pretrained
[rank0]:     ptrs[id_tensor_storage(tensor)].append(name)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/transformers/pytorch_utils.py", line 313, in id_tensor_storage
[rank0]:     unique_id = storage_ptr(tensor)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/safetensors/torch.py", line 17, in storage_ptr
[rank0]:     return tensor.storage().data_ptr()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/storage.py", line 1237, in data_ptr
[rank0]:     return self._data_ptr()
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/storage.py", line 1241, in _data_ptr
[rank0]:     return self._untyped_storage.data_ptr()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: Attempted to access the data pointer on an invalid python storage.
```

A temporary patch that I've been using is this, but it only works when TP=1, when TP>1 then the weights themselves are corrupted. 

```python
target2 = self.init(torch_dtype_from_mcore_config(source.config))
target2.load_state_dict({k:v.cpu() for k,v in target.state_dict().items()})
target2.save_pretrained(...)
```

**Comment by hemildesai** [comment]
Hi, a current workaround is

> edit `devices` in io.json from the checkpoint context to 1 for single gpu. 

These files are embedded in the checkpoint and don't explicitly get updated if one calls `export_ckpt`. We will work on a fix in the meantime.

**Comment by shaltielshmid** [comment]
Hey! Thank you for the response. It didn't seem to work for me, I'm still getting the same errors I was getting before. 

It seems like when I use the TransformerEngine plugin, the checkpoint is loaded onto the GPU even though it shouldn't. Conversely, if I don't use the TE plugin, the export works just fine and doesn't use any GPU memory. 

Right now I encounter 3 crashes:

1. Not enough GPU memory available, when trying to export a checkpoint while still training. 

2. `RuntimeError: CUDA error: an illegal memory access was encountered` => solved by calling CUDA_LAUNCH_BLOCKING=1

3. `RuntimeError: Attempted to access the data pointer on an invalid python storage.` => the `.cpu` call in the export doesn't actually move the parameters. I solved this with initializing again and calling `load_state_dict` (see previous comment).

**Comment by shaltielshmid** [comment]
Update: The solution seems to be the same as in 14375: https://github.com/NVIDIA/NeMo/issues/14375#issuecomment-3197480842
