### ISSUE TITLE
jasper_infer.py causes GPU memory OOM

### ISSUE THREAD

**Issue by Slyne** [NVIDIA/NeMo#35]
Using the script jasper_infer.py according to the tutorial, I find the GPU memory seems not released after each batch and it increases after each batch until OOM.
model_config=/workspace/nemo/examples/asr/configs/jasper10x5dr.yaml
CUDA: 10.1
Tesla V100

**Comment by blisc** [comment]
How large is your infer dataset?

Are you doing multi-gpu inference?

If not, can you change this line https://github.com/NVIDIA/NeMo/blob/master/nemo/nemo/backends/pytorch/actions.py#L808
from `values_dict[key] += [registered_e_tensors[key]]` to `values_dict[key] += [registered_e_tensors[key].cpu()]` and see if it helps?

**Comment by Slyne** [comment]
Thanks, it works now.
