### ISSUE TITLE
RuntimeError Fastpitch Training: Timed out initializing process group in store based barrier on rank: 0

### ISSUE THREAD

**Issue by m-aqeeljanjua** [NVIDIA/NeMo#4418]
I am training a fastpitch model and when I use large data i.e. 21,000 audio files to trainset, I get the following error.
`15247it [58:54,  4.53it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
14572it [58:55,  3.74it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
15334it [59:14,  4.30it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
13797it [59:18,  3.78it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
13836it [59:28,  3.86it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
15461it [59:45,  4.33it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00)
13911it [59:47,  3.76it/s][NeMo W 2022-06-22 12:50:01 nemo_logging:349] /opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py:420: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
      rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")

Error executing job with overrides: ['train_dataset=6670_manifest_other_train.json', 'validation_datasets=6670_manifest_other_dev.json']
15213it [59:40,  4.36it/s]Traceback (most recent call last):
  File "fastpitch_align.py", line 31, in main
    trainer.fit(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1169, in _run
    self.strategy.setup_environment()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 151, in setup_environment
    self.setup_distributed()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in setup_distributed
    init_dist_connection(self.cluster_environment, self._process_group_backend)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 355, in init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 610, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 246, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=7, worker_count=1, timeout=0:30:00
)`
I am training this on 

- 7xA100(80G)
- PyTorch Nvidia container v21.12-py3
- Nemo 1.9.0

**Comment by itzsimpl** [comment]
With "Timed out intializing process group" errors, their source is traditionally earlier in the log, not at the end of the log. 

That being said, could you provide also the nemo version, the environment (barematal or container, in the latter case how you built it), last but not least how you are running the command (e.g. SLURM and its parameters, or other).

This will help in debugging. As it stands, I've noticed your `wolrd_size=7`, but you mention training on `6xA100`. Assuming you are using SLURM, recheck your `sbatch` and `srun` parameters if they are consistent with the setup.

**Comment by m-aqeeljanjua** [comment]
> With "Timed out intializing process group" errors, their source is traditionally earlier in the log, not at the end of the log.
> 
> That being said, could you provide also the nemo version, the environment (barematal or container, in the latter case how you built it), last but not least how you are running the command (e.g. SLURM and its parameters, or other).
> 
> This will help in debugging. As it stands, I've noticed your `wolrd_size=7`, but you mention training on `6xA100`. Assuming you are using SLURM, recheck your `sbatch` and `srun` parameters if they are consistent with the setup.

I am using Nemo 1.9.0 and running this command to run it `fastpitch_align.py --config-name=fastpitch_align_22050.yaml train_dataset=6670_manifest_other_train.json validation_datasets=6670_manifest_other_dev.json`
I am using default config (examples/tts/conf/fastpitch_align_44100.yaml) for the training.

**Comment by ericharper** [comment]
@m-aqeeljanjua , I think you've only pasted a warning message. Can you check the logs more for an error?

**Comment by m-aqeeljanjua** [comment]
> @m-aqeeljanjua , I think you've only pasted a warning message. Can you check the logs more for an error?
@ericharper that's all I have actually. It only happens when I use large-size data, if the training examples are less than 10k then the same model and parameters work fine.

**Comment by itzsimpl** [comment]
@m-aqeeljanjua notice the line
```Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/6```
the last number `/6` indicates that when doing the ddp initialisation, it wa assumed you have a `WOLRD_SIZE=6`, so based on your previous log and responses, something seems off. The best way for helping you debug would be for you to attach the entire log file.

**Comment by m-aqeeljanjua** [comment]
@itzsimpl, the Following is the initial log which I reproduced on the same data.
`
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/6
Created a temporary directory at /tmp/tmpohorrog_
Writing /tmp/tmpohorrog_/_remote_module_non_sriptable.py
4it [00:01,  3.70it/s]Created a temporary directory at /tmp/tmpc47z869b
Writing /tmp/tmpc47z869b/_remote_module_non_sriptable.py
8it [00:02,  3.53it/s]Created a temporary directory at /tmp/tmp3p1jzr36
Writing /tmp/tmp3p1jzr36/_remote_module_non_sriptable.py
18it [00:04,  3.85it/s]Created a temporary directory at /tmp/tmpunras3tk
Writing /tmp/tmpunras3tk/_remote_module_non_sriptable.py
33it [00:08,  3.73it/s]Created a temporary directory at /tmp/tmpmyeh5fva
Writing /tmp/tmpmyeh5fva/_remote_module_non_sriptable.py
20it [00:05,  3.79it/s]Created a temporary directory at /tmp/tmpd8rzjq05
Writing /tmp/tmpd8rzjq05/_remote_module_non_sriptable.py
38it [00:10,  3.70it/s]Created a temporary directory at /tmp/tmp1b2a1a2q
Writing /tmp/tmp1b2a1a2q/_remote_module_non_sriptable.py
7216it [29:46,  3.98it/s]Added key: store_based_barrier_key:1 to store for rank: 0
7209it [29:50,  4.13it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=6, worker_count=1, timeout=
0:30:00)
`
After this step, the following error occurs.

`14503it [59:32,  4.08it/s]Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=6, worker_count=1, timeout
=0:30:00)
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/6
[E socket.cpp:793] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 51363).
Error executing job with overrides: ['train_dataset=9017_manifest_clean_train.json', 'validation_datasets=9017_manifest_clean_dev.json']
Traceback (most recent call last):
  File "/workspace/share/docker2Training/SpeechData/LibriVox_TTS_dataset/hi_fi_tts_v0/fastpitch_align.py", line 31, in main
    trainer.fit(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1169, in _run
    self.strategy.setup_environment()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 151, in setup_environment
    self.setup_distributed()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 191, in setup_distributed
    init_dist_connection(self.cluster_environment, self._process_group_backend)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 355, in init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 597, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 259, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 191, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 51363).
`
Hope this will clearout

**Comment by m-aqeeljanjua** [comment]
@itzsimpl @ericharper, I have solved this issue by reinstalling it from the source using the following command in a pytorch22.01 container.
`apt-get update && apt-get install -y libsndfile1 ffmpeg
git clone https://github.com/NVIDIA/NeMo
cd NeMo
./reinstall.sh`

**Comment by anferico** [comment]
I'm facing the same issue while trying to train FastPitch on 8 A100 GPUs via Docker using PyTorch Lightning's Distributed Data Parallel (DDP) strategy.

In my case, it feels like the issue is caused by the fact that the dataset tokenization process (which by the way takes almost 2 hours for a 40h dataset) is repeated 8 times (once per GPU). Specifically, what seems to happen is that initially just 1 out of the 8 processes spawned by DDP performs the tokenization, however once it's done, the other processes start tokenizing the dataset again from scratch, and they do so concurrently. Eventually, this leads to the exact same error that @m-aqeeljanjua reported.

Now while this doesn't make any sense, it's kind of expected given how DDP works (see [documentation](https://lightning.ai/docs/pytorch/stable/accelerators/gpu_intermediate.html#distributed-data-parallel)). In particular, the documentation clearly states that "_This Lightning implementation of DDP calls your script under the hood multiple times with the correct environment variables_". This means that if your training script contains the dataset tokenization logic (like it does, since the tokenization logic is contained in the [`FastPitchModel`](https://github.com/NVIDIA/NeMo/blob/d3017e4d342627ecebc81b035d5b0839ec899719/nemo/collections/tts/models/fastpitch.py#L77) class), it'll be repeated as many times as the number of GPUs you're using.

To me this feels like a bug at best and bad software design at worst. By the way, I'm facing this issue with NeMo 1.17.0.
Can somebody help me with this? It's quite frustrating not being able to train FastPitch with multiple GPUs.
