### ISSUE TITLE
I could not achieve to run  eval_beamsearch_ngram.py script on my GPU.

### ISSUE THREAD

**Issue by mesut92** [NVIDIA/NeMo#5700]
It is working on CPU but not working on my GPU. I tried Cuda 11.3, 11.8, 12.0 and Python 3.8, 3.9. It did not work. I got same error each time. 
This is how i run the code;
`python eval_beamsearch_ngram.py --nemo_model_file /media/mesut/Depo1/models/49/49.nemo --kenlm_model_file /media/mesut/Depo1/models/tbmmV8/final.nemo  --input_manifest /media/mesut/Depo1/works/NeMo/tools/asr_webapp/manifest_input.json --preds_output_folder out --beam_width 128 --beam_alpha 1 --beam_beta 0`

Error is something like that;
```
Reading Manifest /media/mesut/Depo1/works/NeMo/tools/asr_webapp/manifest_input.json ...: 1it [00:00, 10131.17it/s]
Transcribing:   0%|                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval_beamsearch_ngram.py", line 362, in <module>
    main()
  File "eval_beamsearch_ngram.py", line 269, in main
    all_logits = asr_model.transcribe(audio_file_paths, batch_size=args.acoustic_batch_size, logprobs=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/NeMo/nemo/collections/asr/models/ctc_models.py", line 183, in transcribe
    logits, logits_len, greedy_predictions = self.forward(
  File "/app/NeMo/nemo/core/classes/common.py", line 1084, in __call__
    outputs = wrapped(*args, **kwargs)
  File "/app/NeMo/nemo/collections/asr/models/ctc_models.py", line 536, in forward
    processed_signal, processed_signal_length = self.preprocessor(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/NeMo/nemo/core/classes/common.py", line 1084, in __call__
    outputs = wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/NeMo/nemo/collections/asr/modules/audio_preprocessing.py", line 85, in forward
    processed_signal, processed_length = self.get_features(input_signal, length)
  File "/app/NeMo/nemo/collections/asr/modules/audio_preprocessing.py", line 268, in get_features
    return self.featurizer(input_signal, length)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/NeMo/nemo/collections/asr/parts/preprocessing/features.py", line 350, in forward
    x = self.stft(x)
  File "/app/NeMo/nemo/collections/asr/parts/preprocessing/features.py", line 242, in <lambda>
    self.stft = lambda x: torch.stft(
  File "/usr/local/lib/python3.8/dist-packages/torch/functional.py", line 632, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

```

Ubuntu 20.04
GPU: Gigabyte Windforce 4090

**Comment by titu1994** [comment]
`Kenlm_model_file` is not a Nemo file - you use the train kenlm script on some text data in order to get a .binary file that is an Ngram lm - and pass it to this model.

**Comment by mesut92** [comment]
Actually my `Kenlm_model_file` is not a nemo file. I just put .nemo extension. It is kenlm binary format. I trained with `NeMo/scripts/asr_language_modeling/ngram_lm/train_kenlm.py` . After your response, i trained again but it is same error. It works on CPU but does not work on my GPU.

**Comment by titu1994** [comment]
Did you use conda to install pytorch ? Torch.stft() is a basic operation part of torch itself, cuFFT should be affected only if you somehow incorrectly compiled torch from source I think.

**Comment by mesut92** [comment]
I ran in docker container. I tried cuda version which i mentioned before

And my Dockerfile is something like that;

```
FROM nvidia/cuda:11.3.0-runtime-ubuntu20.04


ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

COPY requirements.txt .
#COPY lint-requirements.txt .

RUN apt-get -yq update \
     && apt-get upgrade -yq \
     && apt-get -yq install apt-utils gcc libpq-dev libsndfile-dev git sox \
     && apt-get install -yq python3.8 python3.8-dev python3-pip libsndfile1 ffmpeg swig wget cmake

RUN ln -sf /usr/bin/python3.8 /usr/bin/python3
RUN ln -sf /usr/bin/python3.8 /usr/bin/python

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113


RUN pip3 install Cython

WORKDIR /app
RUN git clone -b v1.11.0 https://github.com/NVIDIA/NeMo
WORKDIR /app/NeMo

RUN ./reinstall.sh

WORKDIR /app/NeMo/scripts/asr_language_modeling/ngram_lm/
RUN bash install_beamsearch_decoders.sh
```

**Comment by titu1994** [comment]
The dockerfile seems correct. I'm wondering if it's just torch which is incorrect here. Could you try the Nvidia pytorch container as the base and skip all the pytorch install stuff? We have instructions for it in the readme.

**Comment by mesut92** [comment]
I ran that docker command 
```
docker run --gpus all -it --rm -v <nemo_github_folder>:/NeMo --shm-size=8g \
-p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit \
stack=67108864 --device=/dev/snd nvcr.io/nvidia/pytorch:22.08-py3
```
And i went into container, It gave me that warning.

```
WARNING: Detected NVIDIA NVIDIA GeForce RTX 4090 GPU, which is not yet supported in this version of the container
ERROR: No supported GPU(s) detected to run this container
```

Do you have any suggestion?

thanks, Mesut

**Comment by titu1994** [comment]
You probably need to have updated docker and Nvidia drivers. That shows up when the drivers are not the latest

**Comment by mesut92** [comment]
Thanks for your help and quick responses Titu. I guess reason is that " `ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:22.08-py3` ". I updates it as  `ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:22.12-py3` . And it worked. 

Best Regards
Mesut

**Comment by ArtyomZemlyak** [comment]
11.7 CUDA CUFFT not working with 40* cards as I finded on [Nvidia Forum](https://forums.developer.nvidia.com/t/bug-ubuntu-on-wsl2-rtx4090-related-cufft-runtime-error/230883/6).
