### ISSUE TITLE
Numba error while fine-tuning an ASR model

### ISSUE THREAD

**Issue by carlosfranzreb** [NVIDIA/NeMo#5929]
Hello,

I am fine-tuning an ASR model (the English Conformer Transducer) and encountering the following error:

```log
2023-02-03 14:46:28 | numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE |  
-- | -- | --
  |   | 2023-02-03 14:46:28 | raise CudaAPIError(retcode, msg) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 335, in _check_error |  
  |   | 2023-02-03 14:46:28 | self._check_error(fname, retcode) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call |  
  |   | 2023-02-03 14:46:28 | driver.cuLaunchKernel(cufunc_handle, |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2094, in launch_kernel |  
  |   | 2023-02-03 14:46:28 | driver.launch_kernel(cufunc.handle, |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 693, in launch |  
  |   | 2023-02-03 14:46:28 | kernel.launch(args, griddim, blockdim, stream, sharedmem) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 966, in call |  
  |   | 2023-02-03 14:46:28 | return self.dispatcher.call(args, self.griddim, self.blockdim, |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 821, in __call__ |  
  |   | 2023-02-03 14:46:28 | gpu_rnnt_kernel.compute_alphas_kernel[self.minibatch_, self.maxU_, self.stream_, 0]( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/utils/cuda_utils/gpu_rnnt.py", line 161, in compute_cost_and_score |  
  |   | 2023-02-03 14:46:28 | return self.compute_cost_and_score(acts, grads, costs, pad_labels, label_lengths, input_lengths) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/utils/cuda_utils/gpu_rnnt.py", line 249, in cost_and_grad |  
  |   | 2023-02-03 14:46:28 | status = wrapper.cost_and_grad( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt.py", line 223, in rnnt_loss_gpu |  
  |   | 2023-02-03 14:46:28 | loss_func( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt_pytorch.py", line 62, in forward |  
  |   | 2023-02-03 14:46:28 | return self.loss( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt_pytorch.py", line 166, in forward |  
  |   | 2023-02-03 14:46:28 | return forward_call(*input, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl |  
  |   | 2023-02-03 14:46:28 | loss = self._loss(acts=log_probs, labels=targets, act_lens=input_lengths, label_lens=target_lengths) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/losses/rnnt.py", line 288, in forward |  
  |   | 2023-02-03 14:46:28 | loss_batch = self.loss( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/modules/rnnt.py", line 901, in forward |  
  |   | 2023-02-03 14:46:28 | outputs = wrapped(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 963, in __call__ |  
  |   | 2023-02-03 14:46:28 | loss_value, wer, _, _ = self.joint( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/rnnt_models.py", line 710, in training_step |  
  |   | 2023-02-03 14:46:28 | output_dict = wrapped(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/nemo/utils/model_utils.py", line 364, in wrap_training_step |  
  |   | 2023-02-03 14:46:28 | asr_loss = self.asr.training_step(batch, batch_idx)["loss"] |  
  |   | 2023-02-03 14:46:28 | File "/netscratch/franzreb/accent_info/src/model.py", line 121, in training_step |  
  |   | 2023-02-03 14:46:28 | output = self.module.training_step(*inputs, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward |  
  |   | 2023-02-03 14:46:28 | output = self.module(*inputs[0], **kwargs[0]) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 992, in forward |  
  |   | 2023-02-03 14:46:28 | return forward_call(*input, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl |  
  |   | 2023-02-03 14:46:28 | return self.model(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 349, in training_step |  
  |   | 2023-02-03 14:46:28 | output = fn(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook |  
  |   | 2023-02-03 14:46:28 | training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values()) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step |  
  |   | 2023-02-03 14:46:28 | step_output = self._step_fn() |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure |  
  |   | 2023-02-03 14:46:28 | self._result = self.closure(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__ |  
  |   | 2023-02-03 14:46:28 | closure() |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization |  
  |   | 2023-02-03 14:46:28 | result = self._run_optimization( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance |  
  |   | 2023-02-03 14:46:28 | outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance |  
  |   | 2023-02-03 14:46:28 | batch_output = self.batch_loop.run(batch, batch_idx) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run |  
  |   | 2023-02-03 14:46:28 | self._outputs = self.epoch_loop.run(self._data_fetcher) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance |  
  |   | 2023-02-03 14:46:28 | self.advance(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run |  
  |   | 2023-02-03 14:46:28 | self.fit_loop.run() |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train |  
  |   | 2023-02-03 14:46:28 | return self._run_train() |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage |  
  |   | 2023-02-03 14:46:28 | results = self._run_stage() |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run |  
  |   | 2023-02-03 14:46:28 | results = self._run(model, ckpt_path=self.ckpt_path) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl |  
  |   | 2023-02-03 14:46:28 | return trainer_fn(*args, **kwargs) |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt |  
  |   | 2023-02-03 14:46:28 | self._call_and_handle_interrupt( |  
  |   | 2023-02-03 14:46:28 | File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit |  
  |   | 2023-02-03 14:46:28 | trainer.fit(model, train_dataloaders=train_dl) |  
  |   | 2023-02-03 14:46:28 | File "run.py", line 20, in main |  
  |   | 2023-02-03 14:46:28 | main(args) |  
  |   | 2023-02-03 14:46:28 | File "run.py", line 57, in <module> |  
  |   | 2023-02-03 14:46:28 | Traceback (most recent call last):
```

The error always occurs at a similar training step. It is a Numba Cuda API error that happens when calling the ASR model's loss function. Do you know how to address this issue? If not, how can I debug it? Thank you very much for your help.

**Comment by titu1994** [comment]
> Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE

This is almost always a mismatch of cuda toolkit version (install via pytorch conda or manually), Numba version (aim for the latest version if possible), and cuda drivers (again, aim for newer versions). 

Using old cuda with old drivers or numba version will cause this. Best is to use cuda 11.8, Numba 0.56 and latest cuda drivers.

**Comment by carlosfranzreb** [comment]
Thanks for the quick reply!

The same code and installation runs with a different pre-trained model (the German Conformer Transducer, instead of the English version). Also, the error does not occur at the beginning of training; it happens after thousands of batches have been succesfully trained. Could this still be a versioning error, or is there another possible explanation?

**Comment by titu1994** [comment]
Hmm that's less likely but still possible. Could you try a python 3.9 docker, pytorch 1.13 install fe conda and update Numba to 0.56 and see if run continues. Though if it occurs after many thousands of steps it can also point to other issues   

I'd need to take a look at your run script, plus the config to be able to debug this

**Comment by carlosfranzreb** [comment]
Alright, I will try a new container. Sharing the code is a bit complicated. If that wouldn't work, how would you go about debugging this? I could try to do so myself.

**Comment by titu1994** [comment]
Debugging Numba cuda would be problematic. You can try gdb but that doesn't always work. Especially in your case where it doesn't immediate crash. 

You can try the NeMo 1.14 container to see if that works out of the box

**Comment by carlosfranzreb** [comment]
I have tried several Nemo images (1.15, 1.13, 1.10) from the Nvidia NGC cloud, and the error still persists. Our cluster runs with Enroot container, so I import the Docker image with `enroot import`. The training starts as expected, and the predictions are always close to the references. At some point, the Numba error mentioned above pops up: `numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE`.

Attached is a compressed version of my code, where the error also occurs. The train and test manifest file paths are subsets of Common Voice 10.0. Could you have a look at the scripts?

[debug_asr.zip](https://github.com/NVIDIA/NeMo/files/11050660/debug_asr.zip)

**Comment by carlosfranzreb** [comment]
@titu1994, could you re-open the issue?

**Comment by ROZBEH** [comment]
any luck solving this?
I am facing the same issue. My script runs okay without commonvoice, but I start seeing the error when I add commonvoice data.

**Comment by carlosfranzreb** [comment]
There was some error in the datafile. One transcription was super long, including much more text than the transcription. So check that all transcription have reasonable lengths!

**Comment by ROZBEH** [comment]
I'll check that and report back here. Thank you.

**Comment by ROZBEH** [comment]
Also, what length is considered long :-) ?

**Comment by titu1994** [comment]
Interesting, I think I know what's going on. 
CUDA 12 and 11, both have an upper bound on the number of threads that can be launched at once - this is capped at 1024. 

Now, the alphas and betas cuda kernels for RNNT are written sudu that they launch "nax_target_seq_length" threads at once to process entire 4d tensor in one kernel launch (https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/numba/rnnt_loss/utils/cuda_utils/gpu_rnnt.py#L164) (see: max_U). 

In case your target text is super long, even after tokenizarion, it is completely feasible that it's sequence length surpasses 1024. In this case, this cryptic error shows up. Removal of that outlier fixes this.

**Comment by carlosfranzreb** [comment]
@ROZBEH I would just constrain the max. length that is allowed, and keep increasing it until the error occurs. You can do this right after loading a batch.

@titu1994 If you are right, this is something you could easily catch and return an informative error. The Numba error is not very helpful.

**Comment by ROZBEH** [comment]
Thanks to both.
The issue on my end was the actual text and not the length. The dataset is the commonvoice and after removing examples such as below, the issue is gone now.
```
"district in the donaupark a statue of and a plaque for sim\u00f3n bol\u00edvar"
"going swiftly to saint gluten who goes back up to enter a caf\u00e9"
```
